bundler_args: --without development
sudo: false
addons:
  apt:
    packages:
      - lsb-release
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  #  - RAKE_ENV=ci bundle exec rake lint
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.3
env:
  global:
    - LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"
  matrix:
    - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 5.1.0" STRICT_VARIABLES=yes
